// Generated by CoffeeScript 1.9.1
(function() {
  var ShioriLoader, chai, chaiAsPromised, detector, detector_spy, expect, sinon;

  if (typeof require !== "undefined" && require !== null) {
    chai = require('chai');
  } else {
    chai = this.chai;
  }

  chai.should();

  expect = chai.expect;

  if (typeof require !== "undefined" && require !== null) {
    chaiAsPromised = require('chai-as-promised');
  } else {
    chaiAsPromised = this.chaiAsPromised;
  }

  chai.use(chaiAsPromised);

  if (typeof require !== "undefined" && require !== null) {
    sinon = require('sinon');
    ShioriLoader = require('../lib/ShioriLoader.js');
  } else {
    sinon = this.sinon;
    ShioriLoader = this.ShioriLoader;
  }

  ShioriLoader.shiories.dummy = (function() {
    function dummy(fs) {}

    return dummy;

  })();

  detector = function(fs, dirpath) {};

  ShioriLoader.shiori_detectors.push(detector);

  detector_spy = sinon.spy(detector);

  describe('junk', function() {
    return it('should ?', function() {
      var args;
      args = [
        {
          'descript.txt': 'Charset,UTF-8'
        }, '/dummy'
      ];
      ShioriLoader.detect_shiori.apply(ShioriLoader, args);
      return detector_spy.calledWithExactly(args);
    });
  });

}).call(this);
